"""referentiel : annee_scolaire, niveau, matiere, parametre, tarifs

Revision ID: 3e3db18e3679
Revises: 731086e64ea0
Create Date: 2026-08-14 04:01:20.174838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3db18e3679'
down_revision: Union[str, Sequence[str], None] = '731086e64ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annee_scolaire',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('libelle', sa.String(length=9), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_fin > date_debut', name='ck_annee_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_index('ux_annee_active', 'annee_scolaire', ['est_active'], unique=True, postgresql_where=sa.text('est_active'))
    op.create_table('matiere',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('niveau',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('libelle', sa.String(length=60), nullable=False),
    sa.Column('ordre', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('ordre')
    )
    op.create_table('parametre',
    sa.Column('cle', sa.String(length=60), nullable=False),
    sa.Column('valeur', sa.String(), nullable=False),
    sa.Column('type_valeur', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('tarif_eleve',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('annee_scolaire_id', sa.BigInteger(), nullable=False),
    sa.Column('niveau_code', sa.String(length=5), nullable=False),
    sa.Column('matiere_id', sa.BigInteger(), nullable=False),
    sa.Column('montant_cents', sa.BigInteger(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('montant_cents >= 0', name='ck_tarif_eleve_positif'),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.ForeignKeyConstraint(['niveau_code'], ['niveau.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee_scolaire_id', 'niveau_code', 'matiere_id', name='ux_tarif_eleve')
    )
    op.create_table('tarif_professeur',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('annee_scolaire_id', sa.BigInteger(), nullable=False),
    sa.Column('niveau_code', sa.String(length=5), nullable=False),
    sa.Column('matiere_id', sa.BigInteger(), nullable=False),
    sa.Column('montant_par_eleve_cents', sa.BigInteger(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('montant_par_eleve_cents >= 0', name='ck_tarif_prof_positif'),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.ForeignKeyConstraint(['niveau_code'], ['niveau.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee_scolaire_id', 'niveau_code', 'matiere_id', name='ux_tarif_prof')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarif_professeur')
    op.drop_table('tarif_eleve')
    op.drop_table('parametre')
    op.drop_table('niveau')
    op.drop_table('matiere')
    op.drop_index('ux_annee_active', table_name='annee_scolaire', postgresql_where=sa.text('est_active'))
    op.drop_table('annee_scolaire')
    # ### end Alembic commands ###
