"""utilisateur et journal_audit

Revision ID: 731086e64ea0
Revises: 1a3991e20337
Create Date: 2026-08-14 00:04:04.150382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '731086e64ea0'
down_revision: Union[str, Sequence[str], None] = '1a3991e20337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CAISSIER', 'PROFESSEUR', name='role_utilisateur'), nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'PROFESSEUR' AND professeur_id IS NOT NULL) OR (role <> 'PROFESSEUR' AND professeur_id IS NULL)", name='ck_prof_lie'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('utilisateur_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entite', sa.String(length=40), nullable=False),
    sa.Column('entite_id', sa.BigInteger(), nullable=True),
    sa.Column('avant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adresse_ip', postgresql.INET(), nullable=True),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_audit')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
    # Postgres ne supprime pas un type ENUM quand la dernière table qui l'utilise
    # est supprimée : sans ce DROP, un downgrade suivi d'un upgrade échouerait
    # avec "type role_utilisateur already exists".
    sa.Enum(name='role_utilisateur').drop(op.get_bind(), checkfirst=True)
