"""paiements : echeance, ligne_echeance, paiement, FK frais_inscription

Revision ID: 998d2219e3e3
Revises: c75cc0009786
Create Date: 2026-08-15 00:34:28.427657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998d2219e3e3'
down_revision: Union[str, Sequence[str], None] = 'c75cc0009786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echeance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eleve_id', sa.BigInteger(), nullable=False),
    sa.Column('periode', sa.String(length=7), nullable=False),
    sa.Column('montant_du_cents', sa.BigInteger(), nullable=False),
    sa.Column('montant_paye_cents', sa.BigInteger(), nullable=False),
    sa.Column('statut', sa.Enum('NON_PAYE', 'PARTIEL', 'PAYE', name='statut_echeance'), nullable=False),
    sa.Column('genere_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("periode ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name='ck_periode_format'),
    sa.CheckConstraint('montant_du_cents >= 0 AND montant_paye_cents >= 0', name='ck_echeance_montants'),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_id', 'periode', name='ux_echeance')
    )
    op.create_index('ix_echeance_impayes', 'echeance', ['periode', 'statut'], unique=False, postgresql_where=sa.text("statut <> 'PAYE'"))
    op.create_table('paiement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('numero_recu', sa.String(length=20), nullable=False),
    sa.Column('eleve_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('MENSUALITE', 'INSCRIPTION', name='type_paiement'), nullable=False),
    sa.Column('periode', sa.String(length=7), nullable=True),
    sa.Column('montant_cents', sa.BigInteger(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('mode', sa.Enum('ESPECES', 'VIREMENT', 'CHEQUE', 'CARTE', 'AUTRE', name='mode_paiement'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('annule_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('annule_par', sa.BigInteger(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.Column('cree_par', sa.BigInteger(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cle_idempotence', sa.UUID(), nullable=True),
    sa.CheckConstraint("(type = 'MENSUALITE' AND periode IS NOT NULL) OR (type = 'INSCRIPTION' AND periode IS NULL)", name='ck_paiement_periode'),
    sa.CheckConstraint('(annule_le IS NULL AND annule_par IS NULL AND motif_annulation IS NULL) OR (annule_le IS NOT NULL AND annule_par IS NOT NULL AND motif_annulation IS NOT NULL)', name='ck_annulation'),
    sa.CheckConstraint('montant_cents > 0', name='ck_paiement_positif'),
    sa.ForeignKeyConstraint(['annule_par'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle_idempotence'),
    sa.UniqueConstraint('numero_recu')
    )
    op.create_index('ix_paiement_date', 'paiement', ['date_paiement'], unique=False, postgresql_where=sa.text('annule_le IS NULL'))
    op.create_index('ix_paiement_eleve', 'paiement', ['eleve_id', 'date_paiement'], unique=False)
    op.create_index('ix_paiement_periode', 'paiement', ['periode'], unique=False, postgresql_where=sa.text('annule_le IS NULL'))
    op.create_table('ligne_echeance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('echeance_id', sa.BigInteger(), nullable=False),
    sa.Column('matiere_id', sa.BigInteger(), nullable=False),
    sa.Column('tarif_cents', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['echeance_id'], ['echeance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('echeance_id', 'matiere_id', name='ux_ligne_echeance')
    )
    op.create_foreign_key(
        'fk_frais_inscription_paiement_id', 'frais_inscription', 'paiement', ['paiement_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_frais_inscription_paiement_id', 'frais_inscription', type_='foreignkey')
    op.drop_table('ligne_echeance')
    op.drop_index('ix_paiement_periode', table_name='paiement', postgresql_where=sa.text('annule_le IS NULL'))
    op.drop_index('ix_paiement_eleve', table_name='paiement')
    op.drop_index('ix_paiement_date', table_name='paiement', postgresql_where=sa.text('annule_le IS NULL'))
    op.drop_table('paiement')
    op.drop_index('ix_echeance_impayes', table_name='echeance', postgresql_where=sa.text("statut <> 'PAYE'"))
    op.drop_table('echeance')
    # ### end Alembic commands ###
    # Postgres ne supprime pas un type ENUM quand la dernière table qui l'utilise
    # est supprimée : sans ça, un downgrade suivi d'un upgrade échouerait avec
    # "type ... already exists".
    sa.Enum(name='mode_paiement').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='type_paiement').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statut_echeance').drop(op.get_bind(), checkfirst=True)
